// data.js — bilingual (ru/en) content tables for the Tavern Builder.
// Every entry carries both languages so the language toggle is instant —
// no rerolling needed. The original handoff entries
// (reference_sources/design_handoff_tavern_builder/design-reference/tavern-data.js) are
// preserved byte-for-byte; later curated additions extend the pools and add
// grammar fields for the name templates. Hand-formatted (.prettierignore).
// adjective: ru = [masc, fem, neut] forms.
// noun: g = 0 masc / 1 fem / 2 neut; ru24 = form after 2–4 («Три Кружки»);
//       enPl = English plural («The Three Tankards»).
// name: gen = Russian genitive («У Барлена»); indeclinable names repeat ru.
const adjs = [
  { ru: ['Пьяный', 'Пьяная', 'Пьяное'], en: 'Drunken' },
  { ru: ['Золочёный', 'Золочёная', 'Золочёное'], en: 'Gilded' },
  { ru: ['Хромой', 'Хромая', 'Хромое'], en: 'Limping' },
  { ru: ['Весёлый', 'Весёлая', 'Весёлое'], en: 'Merry' },
  { ru: ['Ржавый', 'Ржавая', 'Ржавое'], en: 'Rusty' },
  { ru: ['Шепчущий', 'Шепчущая', 'Шепчущее'], en: 'Whispering' },
  { ru: ['Медный', 'Медная', 'Медное'], en: 'Copper' },
  { ru: ['Последний', 'Последняя', 'Последнее'], en: 'Last' },
  { ru: ['Танцующий', 'Танцующая', 'Танцующее'], en: 'Dancing' },
  { ru: ['Слепой', 'Слепая', 'Слепое'], en: 'Blind' },
  { ru: ['Спящий', 'Спящая', 'Спящее'], en: 'Sleeping' },
  { ru: ['Кривой', 'Кривая', 'Кривое'], en: 'Crooked' },
  { ru: ['Бронзовый', 'Бронзовая', 'Бронзовое'], en: 'Bronze' },
  { ru: ['Серебряный', 'Серебряная', 'Серебряное'], en: 'Silver' },
  { ru: ['Чёрный', 'Чёрная', 'Чёрное'], en: 'Black' },
  { ru: ['Белый', 'Белая', 'Белое'], en: 'White' },
  { ru: ['Багровый', 'Багровая', 'Багровое'], en: 'Crimson' },
  { ru: ['Гордый', 'Гордая', 'Гордое'], en: 'Proud' },
  { ru: ['Хитрый', 'Хитрая', 'Хитрое'], en: 'Sly' },
  { ru: ['Сонный', 'Сонная', 'Сонное'], en: 'Drowsy' },
  { ru: ['Громкий', 'Громкая', 'Громкое'], en: 'Loud' },
  { ru: ['Тихий', 'Тихая', 'Тихое'], en: 'Quiet' },
  { ru: ['Голодный', 'Голодная', 'Голодное'], en: 'Hungry' },
  { ru: ['Блудный', 'Блудная', 'Блудное'], en: 'Prodigal' },
  { ru: ['Горелый', 'Горелая', 'Горелое'], en: 'Charred' },
  { ru: ['Треснувший', 'Треснувшая', 'Треснувшее'], en: 'Cracked' },
  { ru: ['Бродячий', 'Бродячая', 'Бродячее'], en: 'Wandering' },
  { ru: ['Каменный', 'Каменная', 'Каменное'], en: 'Stone' },
  { ru: ['Лунный', 'Лунная', 'Лунное'], en: 'Moonlit' },
  { ru: ['Дырявый', 'Дырявая', 'Дырявое'], en: 'Leaky' },
];
const nouns = [
  { ru: 'Кабан', g: 0, ru24: 'Кабана', en: 'Boar', enPl: 'Boars' },
  { ru: 'Грифон', g: 0, ru24: 'Грифона', en: 'Griffin', enPl: 'Griffins' },
  { ru: 'Котёл', g: 0, ru24: 'Котла', en: 'Cauldron', enPl: 'Cauldrons' },
  { ru: 'Фонарь', g: 0, ru24: 'Фонаря', en: 'Lantern', enPl: 'Lanterns' },
  { ru: 'Якорь', g: 0, ru24: 'Якоря', en: 'Anchor', enPl: 'Anchors' },
  { ru: 'Олень', g: 0, ru24: 'Оленя', en: 'Stag', enPl: 'Stags' },
  { ru: 'Гоблин', g: 0, ru24: 'Гоблина', en: 'Goblin', enPl: 'Goblins' },
  { ru: 'Кружка', g: 1, ru24: 'Кружки', en: 'Tankard', enPl: 'Tankards' },
  { ru: 'Русалка', g: 1, ru24: 'Русалки', en: 'Mermaid', enPl: 'Mermaids' },
  { ru: 'Свеча', g: 1, ru24: 'Свечи', en: 'Candle', enPl: 'Candles' },
  { ru: 'Корона', g: 1, ru24: 'Короны', en: 'Crown', enPl: 'Crowns' },
  { ru: 'Роза', g: 1, ru24: 'Розы', en: 'Rose', enPl: 'Roses' },
  { ru: 'Колесо', g: 2, ru24: 'Колеса', en: 'Wheel', enPl: 'Wheels' },
  { ru: 'Ведро', g: 2, ru24: 'Ведра', en: 'Bucket', enPl: 'Buckets' },
  { ru: 'Дракон', g: 0, ru24: 'Дракона', en: 'Dragon', enPl: 'Dragons' },
  { ru: 'Единорог', g: 0, ru24: 'Единорога', en: 'Unicorn', enPl: 'Unicorns' },
  { ru: 'Молот', g: 0, ru24: 'Молота', en: 'Hammer', enPl: 'Hammers' },
  { ru: 'Щит', g: 0, ru24: 'Щита', en: 'Shield', enPl: 'Shields' },
  { ru: 'Клинок', g: 0, ru24: 'Клинка', en: 'Blade', enPl: 'Blades' },
  { ru: 'Башмак', g: 0, ru24: 'Башмака', en: 'Boot', enPl: 'Boots' },
  { ru: 'Петух', g: 0, ru24: 'Петуха', en: 'Rooster', enPl: 'Roosters' },
  { ru: 'Ворон', g: 0, ru24: 'Ворона', en: 'Raven', enPl: 'Ravens' },
  { ru: 'Тролль', g: 0, ru24: 'Тролля', en: 'Troll', enPl: 'Trolls' },
  { ru: 'Странник', g: 0, ru24: 'Странника', en: 'Wanderer', enPl: 'Wanderers' },
  { ru: 'Лис', g: 0, ru24: 'Лиса', en: 'Fox', enPl: 'Foxes' },
  { ru: 'Арфа', g: 1, ru24: 'Арфы', en: 'Harp', enPl: 'Harps' },
  { ru: 'Сова', g: 1, ru24: 'Совы', en: 'Owl', enPl: 'Owls' },
  { ru: 'Подкова', g: 1, ru24: 'Подковы', en: 'Horseshoe', enPl: 'Horseshoes' },
  { ru: 'Звезда', g: 1, ru24: 'Звезды', en: 'Star', enPl: 'Stars' },
  { ru: 'Бочка', g: 1, ru24: 'Бочки', en: 'Barrel', enPl: 'Barrels' },
  { ru: 'Маска', g: 1, ru24: 'Маски', en: 'Mask', enPl: 'Masks' },
  { ru: 'Бутыль', g: 1, ru24: 'Бутыли', en: 'Flagon', enPl: 'Flagons' },
  { ru: 'Копыто', g: 2, ru24: 'Копыта', en: 'Hoof', enPl: 'Hooves' },
  { ru: 'Перо', g: 2, ru24: 'Пера', en: 'Feather', enPl: 'Feathers' },
];

// sign finish — indexed by wealth tier 0..2
const signs = [
  [
    { ru: 'Вывеска облупилась так, что название угадывается с трудом.', en: 'The sign is so weathered the name is barely legible.' },
    { ru: 'Вместо вывески над дверью — доска с грубо намалёванным рисунком.', en: 'Instead of a sign, a plank with a crudely daubed picture hangs over the door.' },
    { ru: 'Вывеску заменяет прибитый над дверью рассохшийся бочонок.', en: 'A cracked keg nailed above the door serves as the sign.' },
    { ru: 'Буквы на вывеске выцвели — местные зовут заведение по-своему.', en: 'The lettering has faded; the locals call the place by their own name.' },
    { ru: 'Вывеска висит на одном гвозде и хлопает при каждом порыве ветра.', en: 'The sign hangs by a single nail and slaps the wall with every gust.' },
  ],
  [
    { ru: 'Аккуратная вывеска недавно подкрашена.', en: 'The tidy sign has been freshly repainted.' },
    { ru: 'Кованая вывеска поскрипывает на ветру.', en: 'A wrought-iron sign creaks in the wind.' },
    { ru: 'Над дверью — резная деревянная вывеска работы местного плотника.', en: 'Above the door hangs a carved wooden sign by the local carpenter.' },
    { ru: 'Вывеска двусторонняя: с одной стороны название, с другой — кружка.', en: 'The sign is two-sided: the name on one face, a tankard on the other.' },
    { ru: 'Под вывеской висит маленький колокольчик для добрых вестей.', en: 'A small bell for good news hangs beneath the sign.' },
  ],
  [
    { ru: 'Вывеска покрыта позолотой и подсвечена парой фонарей.', en: 'The sign is gilded and lit by a pair of lanterns.' },
    { ru: 'Название выложено латунными буквами по полированному дубу.', en: 'The name is set in brass letters on polished oak.' },
    { ru: 'Вывеска из тёмного дерева инкрустирована перламутром.', en: 'The dark-wood sign is inlaid with mother-of-pearl.' },
    { ru: 'Над входом — кованый герб заведения с позолотой.', en: 'A gilded wrought-iron crest of the house hangs over the entrance.' },
    { ru: 'Название подсвечено магическим огоньком, не гаснущим под дождём.', en: 'The name is lit by a magical flame that no rain can put out.' },
  ],
];

// atmosphere fragments per tone
const atmos = {
  cozy: {
    light: [
      { ru: 'В очаге потрескивает огонь, и по стенам пляшут тёплые отсветы.', en: 'A fire crackles in the hearth, throwing warm light across the walls.' },
      { ru: 'Низкие балки увешаны пучками трав, свет мягкий и медовый.', en: 'Bundles of herbs hang from the low beams; the light is soft and honeyed.' },
      { ru: 'Свечи в нишах отбрасывают ровный янтарный свет.', en: 'Candles in wall niches cast a steady amber light.' },
      { ru: 'Сквозь толстые стёкла окон сочится мягкий вечерний свет.', en: 'Soft evening light filters through the thick window panes.' },
      { ru: 'Над стойкой горит лампа с абажуром из цветного стекла.', en: 'A lamp with a stained-glass shade glows above the bar.' },
    ],
    smell: [
      { ru: 'Пахнет свежим хлебом и яблочным сидром.', en: 'It smells of fresh bread and apple cider.' },
      { ru: 'Из кухни тянет жареным луком и тушёным мясом.', en: 'The smell of fried onions and stew drifts from the kitchen.' },
      { ru: 'Пахнет корицей, воском и сушёными яблоками.', en: 'It smells of cinnamon, beeswax and dried apples.' },
      { ru: 'Тянет дымком от очага и свежесваренным супом.', en: 'There is a whiff of hearth smoke and fresh-made soup.' },
      { ru: 'Пахнет мёдом и тёплым молоком с пряностями.', en: 'The air smells of honey and warm spiced milk.' },
    ],
    detail: [
      { ru: 'У огня дремлет старый пёс, не открывая глаз даже на стук двери.', en: 'An old dog dozes by the fire, not even opening an eye at the door.' },
      { ru: 'Над стойкой висит коллекция кружек со всего королевства.', en: 'A collection of tankards from across the realm hangs above the bar.' },
      { ru: 'На каждом столе — свеча в подсвечнике из старой подковы.', en: 'Every table bears a candle in a holder bent from an old horseshoe.' },
      { ru: 'На подоконнике дремлет кот, обёрнутый собственным хвостом.', en: 'A cat dozes on the windowsill, wrapped in its own tail.' },
      { ru: 'У очага сушатся чьи-то варежки и детские башмачки.', en: 'Mittens and a child’s little boots dry by the hearth.' },
      { ru: 'На полке выстроились банки с вареньем, каждая подписана.', en: 'Jars of preserves line a shelf, every one neatly labelled.' },
    ],
  },
  seedy: {
    light: [
      { ru: 'Сальные свечи чадят, и углы зала тонут в темноте.', en: 'Tallow candles smoke, and the corners of the room drown in darkness.' },
      { ru: 'Единственный фонарь над стойкой давно никто не чистил.', en: 'No one has cleaned the single lantern above the bar in years.' },
      { ru: 'Огарок в бутылке — вот и всё освещение этого угла.', en: 'A candle stub in a bottle is all the light this corner gets.' },
      { ru: 'Свет пробивается сквозь ставни, которые не открывали годами.', en: 'Light leaks through shutters that have not been opened in years.' },
      { ru: 'Над стойкой мигает дешёвый алхимический светильник.', en: 'A cheap alchemical lamp flickers above the bar.' },
    ],
    smell: [
      { ru: 'Пахнет прокисшим элем, дымом и мокрой псиной.', en: 'It smells of sour ale, smoke and wet dog.' },
      { ru: 'В воздухе висит сизая пелена дешёвого табака.', en: 'A grey haze of cheap pipe-smoke hangs in the air.' },
      { ru: 'Несёт перегаром, рыбой и чем-то палёным.', en: 'It reeks of stale booze, fish and something singed.' },
      { ru: 'Пахнет сыростью и крысиным гнездом под полом.', en: 'It smells of damp and the rat nest under the floorboards.' },
      { ru: 'В нос бьёт запах дешёвого джина и мокрых опилок.', en: 'The smell of cheap gin and wet sawdust hits the nose.' },
    ],
    detail: [
      { ru: 'На дверном косяке — свежие зарубки от ножа.', en: 'There are fresh knife-marks on the doorframe.' },
      { ru: 'Половицы липнут к подошвам.', en: 'The floorboards stick to your boots.' },
      { ru: 'Вышибала провожает взглядом каждого нового гостя.', en: 'The bouncer follows every newcomer with his eyes.' },
      { ru: 'Под одним из столов кто-то спит — или притворяется.', en: 'Someone is asleep under one of the tables — or pretending to be.' },
      { ru: 'На стене мелом ведут счёт чьих-то долгов.', en: 'Somebody’s debts are chalked up on the wall.' },
      { ru: 'Дверь чёрного хода приоткрыта, и за ней кто-то шепчется.', en: 'The back door stands ajar, and someone is whispering behind it.' },
    ],
  },
  strange: {
    light: [
      { ru: 'Свечи горят зеленоватым пламенем и совсем не оплывают.', en: 'The candles burn with a greenish flame and never seem to melt.' },
      { ru: 'Тени движутся чуть медленнее тех, кто их отбрасывает.', en: 'The shadows move a touch slower than the people casting them.' },
      { ru: 'Огни свечей клонятся в одну сторону, хотя сквозняка нет.', en: 'Every candle flame leans the same way, though there is no draft.' },
      { ru: 'По залу плавают крошечные огоньки, никем не нанятые.', en: 'Tiny motes of light drift about the room, hired by no one.' },
      { ru: 'В окна падает лунный свет — даже в полдень.', en: 'Moonlight falls through the windows — even at noon.' },
    ],
    smell: [
      { ru: 'Пахнет грозой, хотя небо весь день было ясным.', en: 'It smells of thunderstorms, though the sky has been clear all day.' },
      { ru: 'Из погреба тянет ладаном и чем-то очень старым.', en: 'Incense and something very old drift up from the cellar.' },
      { ru: 'Пахнет озоном, как после удара молнии.', en: 'It smells of ozone, as after a lightning strike.' },
      { ru: 'Из-под пола тянет морской солью, хотя море далеко.', en: 'Sea salt drifts up through the floorboards, though the sea is far away.' },
      { ru: 'Каждый чувствует свой запах: кому хлеб, кому дождь, кому пепел.', en: 'Everyone smells something different: bread, rain, ash.' },
    ],
    detail: [
      { ru: 'Часы над стойкой идут против хода.', en: 'The clock above the bar runs backwards.' },
      { ru: 'Одна из дверей ведёт не туда, куда должна.', en: 'One of the doors does not lead where it should.' },
      { ru: 'Кот хозяина смотрит так, будто понимает каждое слово.', en: 'The owner\u2019s cat watches as if it understands every word.' },
      { ru: 'Свечи на одном из столов сами зажигаются к приходу гостя.', en: 'The candles on one table light themselves when a guest arrives.' },
      { ru: 'Зеркало за стойкой отражает зал с опозданием на мгновение.', en: 'The mirror behind the bar reflects the room a heartbeat late.' },
      { ru: 'Меню написано на языке, который понимаешь, пока держишь лист.', en: 'The menu is written in a tongue you understand only while holding the page.' },
    ],
  },
  posh: {
    light: [
      { ru: 'Хрустальные люстры заливают зал ровным тёплым светом.', en: 'Crystal chandeliers flood the hall with steady, warm light.' },
      { ru: 'Свечи в серебряных канделябрах отражаются в начищенной меди.', en: 'Candles in silver candelabras glint off polished brass.' },
      { ru: 'Магические шары света парят под потолком, к вечеру меняя оттенок.', en: 'Magical orbs float beneath the ceiling, shifting hue towards evening.' },
      { ru: 'Свет преломляется в хрустальных графинах на каждом столе.', en: 'Light refracts through the crystal decanters on every table.' },
      { ru: 'Канделябры начищены так, что в них можно смотреться.', en: 'The candelabras are polished to a mirror shine.' },
    ],
    smell: [
      { ru: 'Пахнет воском, пряным вином и дорогим деревом.', en: 'It smells of beeswax, mulled wine and expensive wood.' },
      { ru: 'Из кухни доносится аромат жаркого с пряностями из-за моря.', en: 'From the kitchen drifts a roast seasoned with overseas spices.' },
      { ru: 'Пахнет апельсиновой цедрой и дорогим трубочным табаком.', en: 'It smells of orange peel and expensive pipe tobacco.' },
      { ru: 'В воздухе — тонкий аромат розовой воды и свежей выпечки.', en: 'A delicate scent of rosewater and fresh pastry hangs in the air.' },
      { ru: 'От полированных панелей стен идёт лёгкий запах кедра.', en: 'A faint cedar scent rises from the polished wall panels.' },
    ],
    detail: [
      { ru: 'Полы устланы коврами, заглушающими шаги.', en: 'Thick carpets muffle every footstep.' },
      { ru: 'Стену украшает голова виверны с памятной табличкой.', en: 'A wyvern\u2019s head with a brass plaque adorns the wall.' },
      { ru: 'Официанты двигаются бесшумно, как заговорщики.', en: 'The waiters move as silently as conspirators.' },
      { ru: 'Меню переплетено в кожу с золотым тиснением.', en: 'The menu is bound in leather with gilt lettering.' },
      { ru: 'У входа гостей встречает мажордом с безупречным поклоном.', en: 'A majordomo greets guests at the door with an impeccable bow.' },
      { ru: 'На каждом столе — свежие цветы, сменяемые дважды в день.', en: 'Fresh flowers on every table, changed twice a day.' },
    ],
  },
};

// crowd line — indexed by settlement size 0..2
const crowd = [
  [
    { ru: 'Полдюжины местных знают друг друга с детства и замолкают при чужаках.', en: 'Half a dozen locals have known each other since childhood — and fall silent around strangers.' },
    { ru: 'За столами — пара фермеров и усталый возница.', en: 'A couple of farmers and a tired carter sit at the tables.' },
    { ru: 'Старики у окна бросают ту же пару костей, что и тридцать лет назад.', en: 'The old men by the window roll the same pair of dice they have used for thirty years.' },
    { ru: 'За дальним столом дремлет пастух, его собака следит за залом.', en: 'A shepherd dozes at the far table; his dog keeps watch over the room.' },
    { ru: 'Зал полупуст: все друг друга знают, и разговор один на всех.', en: 'The half-empty room shares a single conversation — everyone knows everyone.' },
  ],
  [
    { ru: 'Зал заполнен наполовину: ремесленники, торговцы, пара наёмников.', en: 'The room is half full: artisans, traders, a pair of sellswords.' },
    { ru: 'Гул разговоров перекрывает стук кружек и кости на дальнем столе.', en: 'The hum of talk drowns out clinking tankards and dice at the far table.' },
    { ru: 'У стойки спорят два торговца, тыча пальцами в счётную книгу.', en: 'Two traders argue at the bar, jabbing at a ledger.' },
    { ru: 'Компания подмастерьев шумно отмечает конец рабочей недели.', en: 'A crowd of apprentices loudly celebrates the end of the working week.' },
    { ru: 'В углу наёмники вполголоса делят аванс.', en: 'In the corner, sellswords quietly split an advance.' },
  ],
  [
    { ru: 'Здесь толпятся гости со всех концов королевства, слышна чужеземная речь.', en: 'Guests from every corner of the realm crowd in; foreign tongues mix in the din.' },
    { ru: 'Между столами снуют посыльные и, вероятно, карманники.', en: 'Messengers — and probably pickpockets — weave between the tables.' },
    { ru: 'Зал гудит на пяти языках, официанты лавируют между столами.', en: 'The hall hums in five tongues; waiters weave between the tables.' },
    { ru: 'За большим столом гильдейские мастера обмывают контракт.', en: 'Guild masters toast a contract at the big table.' },
    { ru: 'У дверей толпится очередь — свободных мест почти нет.', en: 'A queue crowds the door — hardly a free seat left.' },
  ],
];

// menu — [tier0, tier1, tier2]; price strings precomputed per language
const food = [
  [
    { ru: 'Похлёбка из репы', en: 'Turnip stew', pr: '3 мм', pe: '3 cp' },
    { ru: 'Каша с салом', en: 'Porridge with lard', pr: '4 мм', pe: '4 cp' },
    { ru: 'Луковый суп с чёрствым хлебом', en: 'Onion soup with stale bread', pr: '5 мм', pe: '5 cp' },
    { ru: 'Колбаса сомнительного происхождения', en: 'Sausage of uncertain origin', pr: '6 мм', pe: '6 cp' },
    { ru: 'Печёные каштаны', en: 'Roasted chestnuts', pr: '2 мм', pe: '2 cp' },
    { ru: 'Вчерашняя рыба', en: 'Yesterday\u2019s fish', pr: '4 мм', pe: '4 cp' },
    { ru: 'Гороховая каша с дымком', en: 'Smoky pea porridge', pr: '3 мм', pe: '3 cp' },
    { ru: 'Жареные речные пескари', en: 'Fried river gudgeon', pr: '5 мм', pe: '5 cp' },
    { ru: 'Хлебная похлёбка на пиве', en: 'Bread-and-ale sop', pr: '4 мм', pe: '4 cp' },
    { ru: 'Варёные яйца с золой и солью', en: 'Boiled eggs with ash salt', pr: '2 мм', pe: '2 cp' },
    { ru: 'Капустные котлеты', en: 'Cabbage cakes', pr: '3 мм', pe: '3 cp' },
    { ru: 'Сухари с салом и луком', en: 'Hardtack with lard and onion', pr: '2 мм', pe: '2 cp' },
  ],
  [
    { ru: 'Жаркое из кролика', en: 'Rabbit stew', pr: '4 см', pe: '4 sp' },
    { ru: 'Пирог с почками', en: 'Kidney pie', pr: '3 см', pe: '3 sp' },
    { ru: 'Курица в меду', en: 'Honey-glazed chicken', pr: '5 см', pe: '5 sp' },
    { ru: 'Рыба на углях', en: 'Charcoal-grilled fish', pr: '3 см', pe: '3 sp' },
    { ru: 'Баранья нога с травами', en: 'Leg of lamb with herbs', pr: '6 см', pe: '6 sp' },
    { ru: 'Грибная запеканка', en: 'Mushroom casserole', pr: '2 см', pe: '2 sp' },
    { ru: 'Гуляш из говядины с клёцками', en: 'Beef goulash with dumplings', pr: '5 см', pe: '5 sp' },
    { ru: 'Утка с яблоками', en: 'Duck with apples', pr: '7 см', pe: '7 sp' },
    { ru: 'Свиные рёбра в пивной глазури', en: 'Ale-glazed pork ribs', pr: '6 см', pe: '6 sp' },
    { ru: 'Сырная тарелка с орехами', en: 'Cheese board with nuts', pr: '4 см', pe: '4 sp' },
    { ru: 'Пирог с лесными ягодами', en: 'Forest-berry pie', pr: '3 см', pe: '3 sp' },
    { ru: 'Колбаски на гриле с горчицей', en: 'Grilled sausages with mustard', pr: '4 см', pe: '4 sp' },
  ],
  [
    { ru: 'Фазан в винном соусе', en: 'Pheasant in wine sauce', pr: '3 зм', pe: '3 gp' },
    { ru: 'Оленина с можжевельником', en: 'Venison with juniper', pr: '2 зм', pe: '2 gp' },
    { ru: 'Угорь в сливках', en: 'Eel in cream', pr: '2 зм', pe: '2 gp' },
    { ru: 'Кабан, томлённый в пряностях', en: 'Spiced slow-roast boar', pr: '4 зм', pe: '4 gp' },
    { ru: 'Пирог с дичью и трюфелями', en: 'Game pie with truffles', pr: '3 зм', pe: '3 gp' },
    { ru: 'Засахаренные фрукты из-за моря', en: 'Candied fruit from overseas', pr: '1 зм', pe: '1 gp' },
    { ru: 'Лосось на кедровой доске', en: 'Cedar-plank salmon', pr: '3 зм', pe: '3 gp' },
    { ru: 'Перепела в медовой глазури', en: 'Honey-glazed quail', pr: '2 зм', pe: '2 gp' },
    { ru: 'Телятина под трюфельным соусом', en: 'Veal in truffle sauce', pr: '4 зм', pe: '4 gp' },
    { ru: 'Устрицы на льду с лимоном', en: 'Oysters on ice with lemon', pr: '5 зм', pe: '5 gp' },
    { ru: 'Шоколадный фондан с вишней', en: 'Chocolate fondant with cherries', pr: '2 зм', pe: '2 gp' },
    { ru: 'Сыр с голубой плесенью и грушей', en: 'Blue cheese with pear', pr: '3 зм', pe: '3 gp' },
  ],
];
const drinks = [
  [
    { ru: 'Разбавленный эль', en: 'Watered-down ale', pr: '1 мм', pe: '1 cp' },
    { ru: 'Мутный сидр', en: 'Cloudy cider', pr: '2 мм', pe: '2 cp' },
    { ru: 'Самогон «не спрашивай»', en: '\u201cDon\u2019t ask\u201d moonshine', pr: '3 мм', pe: '3 cp' },
    { ru: 'Кипяток с мятой', en: 'Hot water with mint', pr: '1 мм', pe: '1 cp' },
    { ru: 'Кислое вино из бочки', en: 'Sour barrel wine', pr: '2 мм', pe: '2 cp' },
    { ru: 'Травяной отвар «от всего»', en: '“Cure-all” herbal brew', pr: '1 мм', pe: '1 cp' },
    { ru: 'Брага по рецепту хозяина', en: 'The owner’s own hooch', pr: '3 мм', pe: '3 cp' },
    { ru: 'Пиво вчерашнего розлива', en: 'Yesterday’s ale, re-tapped', pr: '2 мм', pe: '2 cp' },
    { ru: 'Козье молоко (свежесть не гарантируется)', en: 'Goat milk (freshness not guaranteed)', pr: '1 мм', pe: '1 cp' },
  ],
  [
    { ru: 'Тёмный эль', en: 'Dark ale', pr: '8 мм', pe: '8 cp' },
    { ru: 'Пряный мёд', en: 'Spiced mead', pr: '1 см', pe: '1 sp' },
    { ru: 'Гномий стаут', en: 'Dwarven stout', pr: '2 см', pe: '2 sp' },
    { ru: 'Яблочный бренди', en: 'Apple brandy', pr: '2 см', pe: '2 sp' },
    { ru: 'Светлый лагер с лимонной коркой', en: 'Pale lager with lemon peel', pr: '1 см', pe: '1 sp' },
    { ru: 'Грог с маслом и специями', en: 'Buttered spice grog', pr: '2 см', pe: '2 sp' },
    { ru: 'Вишнёвая наливка', en: 'Cherry cordial', pr: '2 см', pe: '2 sp' },
    { ru: 'Сидр сухой, прошлогодний', en: 'Dry cider, last year’s press', pr: '1 см', pe: '1 sp' },
    { ru: 'Глинтвейн по полуэльфийскому рецепту', en: 'Half-elven mulled wine', pr: '2 см', pe: '2 sp' },
  ],
  [
    { ru: 'Эльфийское вино', en: 'Elven wine', pr: '1 зм', pe: '1 gp' },
    { ru: 'Выдержанный бренди', en: 'Aged brandy', pr: '2 зм', pe: '2 gp' },
    { ru: 'Игристое из долины', en: 'Valley sparkling wine', pr: '2 зм', pe: '2 gp' },
    { ru: 'Огненное виски с севера', en: 'Northern fire-whisky', pr: '1 зм', pe: '1 gp' },
    { ru: 'Столетний портвейн из погреба', en: 'Century port from the cellar', pr: '3 зм', pe: '3 gp' },
    { ru: 'Ледяное вино с горных виноградников', en: 'Icewine from mountain vineyards', pr: '2 зм', pe: '2 gp' },
    { ru: 'Гномий мёд тройной выдержки', en: 'Triple-aged dwarven mead', pr: '2 зм', pe: '2 gp' },
    { ru: 'Абсент с серебряной ложечкой', en: 'Absinthe with a silver spoon', pr: '3 зм', pe: '3 gp' },
    { ru: 'Игристое из долины фей', en: 'Sparkling wine of the fey vale', pr: '4 зм', pe: '4 gp' },
  ],
];

const names = [
  { ru: 'Барлен', gen: 'Барлена', en: 'Barlen' }, { ru: 'Мирра', gen: 'Мирры', en: 'Mirra' }, { ru: 'Тоск', gen: 'Тоска', en: 'Tosk' },
  { ru: 'Ольда', gen: 'Ольды', en: 'Olda' }, { ru: 'Финн', gen: 'Финна', en: 'Finn' }, { ru: 'Грета', gen: 'Греты', en: 'Greta' },
  { ru: 'Дарвиш', gen: 'Дарвиша', en: 'Darvish' }, { ru: 'Юна', gen: 'Юны', en: 'Yuna' }, { ru: 'Корвин', gen: 'Корвина', en: 'Corwin' },
  { ru: 'Беса', gen: 'Бесы', en: 'Bessa' }, { ru: 'Хальрик', gen: 'Хальрика', en: 'Halrik' }, { ru: 'Тилли', gen: 'Тилли', en: 'Tilly' },
  { ru: 'Орен', gen: 'Орена', en: 'Oren' }, { ru: 'Васка', gen: 'Васки', en: 'Vaska' }, { ru: 'Демм', gen: 'Демма', en: 'Demm' },
  { ru: 'Илша', gen: 'Илши', en: 'Ilsha' }, { ru: 'Готрик', gen: 'Готрика', en: 'Gotrik' }, { ru: 'Перра', gen: 'Перры', en: 'Perra' },
  { ru: 'Сольвей', gen: 'Сольвея', en: 'Solvey' }, { ru: 'Брандт', gen: 'Брандта', en: 'Brandt' }, { ru: 'Ника', gen: 'Ники', en: 'Nika' },
  { ru: 'Ульф', gen: 'Ульфа', en: 'Ulf' }, { ru: 'Магда', gen: 'Магды', en: 'Magda' }, { ru: 'Кессо', gen: 'Кессо', en: 'Kesso' },
  { ru: 'Рутгер', gen: 'Рутгера', en: 'Rutger' }, { ru: 'Зана', gen: 'Заны', en: 'Zana' }, { ru: 'Фолке', gen: 'Фолке', en: 'Folke' },
  { ru: 'Ирма', gen: 'Ирмы', en: 'Irma' },
];
const races = [
  { ru: 'человек', en: 'human' }, { ru: 'дварф', en: 'dwarf' }, { ru: 'полурослик', en: 'halfling' },
  { ru: 'полуэльф', en: 'half-elf' }, { ru: 'полуорк', en: 'half-orc' }, { ru: 'гном', en: 'gnome' },
  { ru: 'тифлинг', en: 'tiefling' }, { ru: 'драконорождённый', en: 'dragonborn' },
  { ru: 'эльф', en: 'elf' }, { ru: 'орк', en: 'orc' }, { ru: 'гоблин', en: 'goblin' },
  { ru: 'табакси', en: 'tabaxi' },
];
const traits = [
  { ru: 'Бывший наёмник — шрамы видно даже под рубахой.', en: 'A former sellsword — the scars show even through the shirt.' },
  { ru: 'Помнит каждый долг до последней монеты.', en: 'Remembers every debt down to the last coin.' },
  { ru: 'Не задаёт вопросов и того же ждёт от гостей.', en: 'Asks no questions and expects the same of the guests.' },
  { ru: 'Знает всё, что происходит в округе.', en: 'Knows everything that happens in the district.' },
  { ru: 'Готовит сам и страшно этим гордится.', en: 'Cooks personally and is fiercely proud of it.' },
  { ru: 'Со всеми говорит как со старыми друзьями.', en: 'Talks to everyone like an old friend.' },
  { ru: 'Суеверен: на каждой балке висит оберег.', en: 'Superstitious: a charm hangs on every beam.' },
  { ru: 'Когда-то выступал в столичном театре.', en: 'Once performed in a capital theatre.' },
  { ru: 'Бывшая жрица: благословляет каждую новую бочку.', en: 'A former priestess: blesses every new cask.' },
  { ru: 'Выиграл таверну в карты — и этим гордится.', en: 'Won the tavern at cards and is proud of it.' },
  { ru: 'Глуховат на левое ухо: наклоняется к собеседнику правым.', en: 'Half-deaf in the left ear: leans in with the right.' },
  { ru: 'Ведёт переписку с десятком трактирщиков из других городов.', en: 'Keeps up letters with a dozen innkeepers in other towns.' },
  { ru: 'Не наливает в долг никому — ни королю, ни нищему.', en: 'Extends credit to no one — king or beggar.' },
  { ru: 'Собирает истории постояльцев в толстую тетрадь.', en: 'Collects guests’ stories in a thick notebook.' },
  { ru: 'Бывший корабельный кок: презирает «сухопутную» кухню.', en: 'A former ship’s cook: scorns “landlubber” cooking.' },
  { ru: 'Помнит вкусы каждого, кто заходил хотя бы дважды.', en: 'Remembers the tastes of anyone who has come in twice.' },
  { ru: 'Держит за стойкой арбалет и зовёт его по имени.', en: 'Keeps a crossbow behind the bar and calls it by name.' },
  { ru: 'Сменил имя, и старое здесь произносить не стоит.', en: 'Changed names; the old one is best not spoken here.' },
  { ru: 'Откладывает каждую десятую монету «на чёрный день гильдии».', en: 'Sets aside every tenth coin “for the guild’s rainy day”.' },
  { ru: 'Не скажет ни слова, пока гость не сделает заказ.', en: 'Says not a word until the guest orders.' },
];
const quirks = [
  { ru: 'Протирает одну и ту же кружку весь вечер.', en: 'Polishes the same tankard all evening.' },
  { ru: 'Говорит о таверне «она», как о корабле.', en: 'Calls the tavern \u201cshe\u201d, like a ship.' },
  { ru: 'Держит ворона, который подслушивает гостей.', en: 'Keeps a raven that eavesdrops on the guests.' },
  { ru: 'Никогда не выходит из-за стойки.', en: 'Never steps out from behind the bar.' },
  { ru: 'Насвистывает один и тот же мотив.', en: 'Whistles the same tune over and over.' },
  { ru: 'Записывает что-то в потрёпанную книжицу.', en: 'Scribbles notes in a battered little book.' },
  { ru: 'Пробует каждое блюдо перед подачей.', en: 'Tastes every dish before it goes out.' },
  { ru: 'Зовёт всех гостей «капитан».', en: 'Calls every guest \u201ccaptain\u201d.' },
  { ru: 'Считает вслух сдачу, даже когда её нет.', en: 'Counts change aloud, even when there is none.' },
  { ru: 'Гладит дверной косяк, проходя мимо, — «на удачу».', en: 'Pats the doorframe in passing — “for luck”.' },
  { ru: 'Носит за ухом гусиное перо, которым никогда не пишет.', en: 'Keeps a goose quill behind one ear and never writes with it.' },
  { ru: 'Пробует монеты на зуб, не глядя на гостя.', en: 'Bites every coin without looking up at the guest.' },
  { ru: 'Разговаривает с очагом, когда думает, что никто не слышит.', en: 'Talks to the hearth when no one seems to listen.' },
  { ru: 'Всегда ставит кружку точно на её старое пятно.', en: 'Sets every tankard exactly on its own old ring-stain.' },
  { ru: 'Меняет серьгу в ухе по дням недели.', en: 'Wears a different earring for each day of the week.' },
  { ru: 'Здоровается с гостями на трёх языках подряд.', en: 'Greets guests in three languages, one after another.' },
  { ru: 'Хрустит пальцами перед тем, как назвать цену.', en: 'Cracks his knuckles before naming a price.' },
  { ru: 'Едва заметно усмехается, услышав враньё.', en: 'Smirks ever so slightly at a lie.' },
  { ru: 'Держит под стойкой блюдце молока «для домового».', en: 'Keeps a saucer of milk under the bar “for the house spirit”.' },
  { ru: 'Записывает заказы углём прямо на столешнице.', en: 'Chalks orders straight onto the bar top in charcoal.' },
];
const secrets = [
  { ru: 'Должен крупную сумму гильдии воров.', en: 'Owes the thieves\u2019 guild a serious sum.' },
  { ru: 'Прячет беглеца в погребе.', en: 'Is hiding a fugitive in the cellar.' },
  { ru: 'Таверна стоит на замурованном входе в подземелье.', en: 'The tavern sits on a bricked-up dungeon entrance.' },
  { ru: 'Скупает краденое — но только у проверенных людей.', en: 'Fences stolen goods — but only for trusted faces.' },
  { ru: 'Это не настоящий хозяин: настоящий исчез год назад.', en: 'Not the real owner: the real one vanished a year ago.' },
  { ru: 'Платит страже, чтобы сюда не заглядывали.', en: 'Pays the watch to keep clear of the place.' },
  { ru: 'Хранит под половицей карту, за которой идёт охота.', en: 'Keeps a much-hunted map under a floorboard.' },
  { ru: 'Состоит в культе, о котором не говорят вслух.', en: 'Belongs to a cult no one names aloud.' },
  { ru: 'Из подвала есть ход в старую канализацию.', en: 'A passage in the cellar leads to the old sewers.' },
  { ru: 'Хранит письмо, способное разорить городского советника.', en: 'Keeps a letter that could ruin a town councillor.' },
  { ru: 'Когда-то служил палачом и узнаёт старых «клиентов».', en: 'Once served as an executioner and recognises old “clients”.' },
  { ru: 'Разбавляет дорогое вино — но только хамам.', en: 'Waters the expensive wine — but only for rude guests.' },
  { ru: 'Платит банде, чтобы в зале никогда не дрались.', en: 'Pays a gang to keep brawls out of the common room.' },
  { ru: 'В погребе зарыт чужой сундук, ключа от которого нет.', en: 'A stranger’s chest is buried in the cellar — no key to it.' },
  { ru: 'Один из постояльцев не выходил из комнаты уже год.', en: 'One lodger has not left his room in a year.' },
  { ru: 'Получает по ночам почту, адресованную мёртвому человеку.', en: 'Receives night mail addressed to a dead man.' },
  { ru: 'Это уже третья таверна: первые две сгорели.', en: 'This is the third tavern: the first two burned down.' },
  { ru: 'Сдаёт комнату над конюшней тому, о ком молчит даже шёпотом.', en: 'Rents the room over the stable to someone never spoken of, even in whispers.' },
  { ru: 'Дважды в месяц выручка уходит в храм — похоже на откуп.', en: 'Twice a month the takings go to a temple — it looks like a payoff.' },
  { ru: 'Знает, где зарыт прежний хозяин. Никто не спрашивал.', en: 'Knows where the previous owner is buried. No one has asked.' },
];
const staff = [
  { role: { ru: 'Подавальщица', en: 'Serving girl' }, detail: { ru: 'слышит больше, чем показывает', en: 'hears more than she lets on' } },
  { role: { ru: 'Вышибала', en: 'Bouncer' }, detail: { ru: 'бывший гладиатор и добрейшая душа', en: 'an ex-gladiator and the gentlest soul' } },
  { role: { ru: 'Повар', en: 'Cook' }, detail: { ru: 'ругается на трёх языках, готовит на пяти', en: 'swears in three languages, cooks in five' } },
  { role: { ru: 'Конюх', en: 'Stablehand' }, detail: { ru: 'знает всех лошадей в округе по именам', en: 'knows every horse in the district by name' } },
  { role: { ru: 'Бард при заведении', en: 'House bard' }, detail: { ru: 'играет за еду и сплетни', en: 'plays for food and gossip' } },
  { role: { ru: 'Посудомой', en: 'Scullery lad' }, detail: { ru: 'мечтает стать приключенцем', en: 'dreams of becoming an adventurer' } },
  { role: { ru: 'Помощник за стойкой', en: 'Barback' }, detail: { ru: 'племянник хозяина, считает каждую монету', en: 'the owner\u2019s nephew, counts every coin' } },
  { role: { ru: 'Кухарка', en: 'Kitchen maid' }, detail: { ru: 'солит всё дважды и не признаёт этого', en: 'salts everything twice and denies it' } },
  { role: { ru: 'Виночерпий', en: 'Cellarman' }, detail: { ru: 'знает каждый бочонок, как родного', en: 'knows every cask like family' } },
  { role: { ru: 'Девочка на побегушках', en: 'Errand girl' }, detail: { ru: 'знает все короткие пути в квартале', en: 'knows every shortcut in the district' } },
  { role: { ru: 'Старый слуга', en: 'Old retainer' }, detail: { ru: 'служил ещё прежнему хозяину и о многом молчит', en: 'served the previous owner and keeps much to himself' } },
  { role: { ru: 'Музыкантша', en: 'Fiddler' }, detail: { ru: 'играет веселее, когда в зале назревает ссора', en: 'plays merrier whenever a quarrel brews' } },
  { role: { ru: 'Привратник', en: 'Doorman' }, detail: { ru: 'пускает по лицам, а не по монетам', en: 'admits by faces, not by coin' } },
  { role: { ru: 'Прачка', en: 'Laundress' }, detail: { ru: 'находит в карманах постояльцев странные вещи', en: 'finds strange things in lodgers’ pockets' } },
  { role: { ru: 'Мальчишка-фонарщик', en: 'Lamp boy' }, detail: { ru: 'зажигает огни и подслушивает у окон', en: 'lights the lamps and eavesdrops at windows' } },
  { role: { ru: 'Вышибала на полставки', en: 'Part-time bouncer' }, detail: { ru: 'днём — каменщик, кулаки как кирпичи', en: 'a mason by day, fists like bricks' } },
];
const patrons = [
  { who: { ru: 'Наёмница в потёртой кольчуге', en: 'A sellsword in worn mail' }, doing: { ru: 'точит нож и поглядывает на дверь', en: 'whets a knife and keeps an eye on the door' } },
  { who: { ru: 'Седой картограф', en: 'A grizzled cartographer' }, doing: { ru: 'раскладывает карты, бормоча о белых пятнах', en: 'spreads out maps, muttering about blank spots' } },
  { who: { ru: 'Пара контрабандистов', en: 'A pair of smugglers' }, doing: { ru: 'спорят шёпотом над списком грузов', en: 'argue in whispers over a cargo list' } },
  { who: { ru: 'Жрец в дорожной рясе', en: 'A priest in travel robes' }, doing: { ru: 'благословляет каждого, кто подсаживается', en: 'blesses anyone who sits down beside him' } },
  { who: { ru: 'Студент академии', en: 'An academy student' }, doing: { ru: 'проигрывает в кости последние деньги', en: 'is gambling away his last coins at dice' } },
  { who: { ru: 'Охотница на чудовищ', en: 'A monster hunter' }, doing: { ru: 'молча пьёт; мешок у её ног только что шевельнулся', en: 'drinks in silence; the sack at her feet just moved' } },
  { who: { ru: 'Старик с попугаем', en: 'An old man with a parrot' }, doing: { ru: 'рассказывает о морях всем, кто готов слушать', en: 'tells sea stories to anyone who will listen' } },
  { who: { ru: 'Гонец в королевских цветах', en: 'A courier in royal colours' }, doing: { ru: 'ест, не снимая перчаток, и явно торопится', en: 'eats without removing his gloves, clearly in a hurry' } },
  { who: { ru: 'Трое шахтёров', en: 'Three miners' }, doing: { ru: 'празднуют что-то с мрачными лицами', en: 'celebrate something with grim faces' } },
  { who: { ru: 'Дама в дорогом плаще', en: 'A lady in an expensive cloak' }, doing: { ru: 'явно ждёт того, кто не приходит', en: 'is clearly waiting for someone who isn\u2019t coming' } },
  { who: { ru: 'Полурослик-торговец', en: 'A halfling trader' }, doing: { ru: 'предлагает всем «настоящие» амулеты', en: 'offers everyone \u201cgenuine\u201d amulets' } },
  { who: { ru: 'Молчаливый воин с севера', en: 'A silent northern warrior' }, doing: { ru: 'занял стол у стены, откуда виден весь зал', en: 'has taken the wall table with a view of the whole room' } },
  { who: { ru: 'Гном-часовщик', en: 'A gnome clockmaker' }, doing: { ru: 'чинит часы прямо за столом, окружённый шестерёнками', en: 'repairs a watch right at the table, ringed by tiny gears' } },
  { who: { ru: 'Пара послушниц', en: 'Two novice nuns' }, doing: { ru: 'спорят о теологии над одной кружкой на двоих', en: 'argue theology over a single shared tankard' } },
  { who: { ru: 'Сборщик налогов', en: 'A tax collector' }, doing: { ru: 'ест в одиночестве: к нему никто не подсаживается', en: 'eats alone: no one will sit with him' } },
  { who: { ru: 'Бард с перевязанной рукой', en: 'A bard with a bandaged hand' }, doing: { ru: 'напевает балладу о собственном поражении', en: 'hums a ballad about his own defeat' } },
  { who: { ru: 'Старуха с клюкой', en: 'An old woman with a cane' }, doing: { ru: 'знает по имени каждого, кто моложе шестидесяти', en: 'calls everyone under sixty by name' } },
  { who: { ru: 'Близнецы-лесорубы', en: 'Twin woodcutters' }, doing: { ru: 'заканчивают фразы друг за друга', en: 'finish each other’s sentences' } },
  { who: { ru: 'Заезжий алхимик', en: 'A travelling alchemist' }, doing: { ru: 'капает что-то в свой эль и записывает результат', en: 'drips something into his ale and notes the result' } },
  { who: { ru: 'Стражник не при службе', en: 'An off-duty watchman' }, doing: { ru: 'сидит спиной к стене и лицом к двери', en: 'sits with his back to the wall, facing the door' } },
  { who: { ru: 'Худой писарь', en: 'A gaunt scribe' }, doing: { ru: 'переписывает чужие письма за выпивку', en: 'copies letters for drink' } },
  { who: { ru: 'Охотник с пустым ягдташем', en: 'A hunter with an empty game bag' }, doing: { ru: 'рассказывает, какого зверя «почти взял»', en: 'tells of the beast he “almost had”' } },
  { who: { ru: 'Вдова в трауре', en: 'A widow in mourning' }, doing: { ru: 'третий вечер заказывает два прибора', en: 'orders two places for the third evening running' } },
  { who: { ru: 'Молодожёны', en: 'A newlywed couple' }, doing: { ru: 'считают медяки на комнату, держась за руки', en: 'count coppers for a room, holding hands' } },
  { who: { ru: 'Гонец гильдии магов', en: 'A mages’ guild courier' }, doing: { ru: 'его сумка изредка шевелится сама', en: 'his satchel stirs on its own now and then' } },
  { who: { ru: 'Картёжник с честным лицом', en: 'A gambler with an honest face' }, doing: { ru: 'лицо слишком честное, чтобы быть честным', en: 'too honest a face to be honest' } },
  { who: { ru: 'Паломник с посохом', en: 'A pilgrim with a staff' }, doing: { ru: 'рисует углём карту на собственном плаще', en: 'sketches a charcoal map on his own cloak' } },
  { who: { ru: 'Кузнец после смены', en: 'A smith after his shift' }, doing: { ru: 'пьёт молча, копоть смыта только с ладоней', en: 'drinks in silence, soot washed only from his palms' } },
  { who: { ru: 'Незнакомка под вуалью', en: 'A veiled stranger' }, doing: { ru: 'заказала лучшее вино и не притронулась к нему', en: 'ordered the best wine and has not touched it' } },
  { who: { ru: 'Драконорождённый счетовод', en: 'A dragonborn bookkeeper' }, doing: { ru: 'щёлкает костяшками счёт быстрее, чем говорит', en: 'clicks abacus beads faster than he speaks' } },
];
const rumors = [
  { ru: 'На старой мельнице по ночам горит свет, хотя мельник умер зимой.', en: 'A light burns in the old mill at night, though the miller died last winter.', truth: 'true' },
  { ru: 'Караваны на южном тракте грабит не банда, а кто-то из стражи.', en: 'It isn\u2019t bandits robbing the south road caravans — it\u2019s someone in the watch.', truth: 'half' },
  { ru: 'В колодце на площади слышали голос, зовущий людей по именам.', en: 'A voice was heard in the square well, calling people by name.', truth: 'false' },
  { ru: 'Барон ищет тихих людей для тихой работы. Платит золотом.', en: 'The baron is hiring quiet folk for quiet work. Pays in gold.', truth: 'true' },
  { ru: 'Из храма пропала реликвия, и жрецы делают вид, что всё в порядке.', en: 'A relic vanished from the temple, and the priests pretend all is well.', truth: 'true' },
  { ru: 'Говорят, под старым рынком есть второй город.', en: 'They say there is a second city beneath the old market.', truth: 'half' },
  { ru: 'Знахарка с окраины скупает волчьи зубы. Десятками.', en: 'The hedge-witch on the edge of town is buying wolf teeth. By the dozen.', truth: 'true' },
  { ru: 'Принцесса сбежала из столицы и путешествует под чужим именем.', en: 'The princess fled the capital and travels under a false name.', truth: 'false' },
  { ru: 'В лесу нашли поляну, где не растёт трава и стрелка компаса крутится.', en: 'They found a clearing where no grass grows and compass needles spin.', truth: 'true' },
  { ru: 'Со следующей луны вводят новый налог на приключенцев.', en: 'A new tax on adventurers comes in at the next moon.', truth: 'false' },
  { ru: 'Хозяин «Золотого якоря» в порту платит за карты морского дна.', en: 'The owner of the Golden Anchor down at the port pays for seabed charts.', truth: 'half' },
  { ru: 'На севере снова видели драконьи огни.', en: 'Dragon-fires were seen in the north again.', truth: 'half' },
  { ru: 'Паром у южного брода ходит и ночью — если заплатить двойную цену.', en: 'The ferry at the south ford runs at night too — for double the fare.', truth: 'true' },
  { ru: 'В заброшенной сторожевой башне поселился отшельник, лечащий травами.', en: 'A hermit healer has settled in the abandoned watchtower.', truth: 'true' },
  { ru: 'Гильдия каменщиков набирает охрану для какого-то подземного заказа.', en: 'The masons’ guild is hiring guards for some underground job.', truth: 'true' },
  { ru: 'Старый колодец за кузней зимой не замерзает.', en: 'The old well behind the smithy never freezes in winter.', truth: 'true' },
  { ru: 'Купец Орвальд скупает любые карты гор, даже фальшивые.', en: 'Merchant Orvald buys any mountain maps, even forged ones.', truth: 'true' },
  { ru: 'Ночной сторож видел огни на старом кладбище. Дважды.', en: 'The night watchman saw lights in the old graveyard. Twice.', truth: 'half' },
  { ru: 'В реке под мостом живёт нечто, ворующее бельё с берега.', en: 'Something lives under the bridge and steals laundry from the bank.', truth: 'half' },
  { ru: 'Жена мельника говорит с воронами — и они отвечают.', en: 'The miller’s wife talks to ravens — and they answer.', truth: 'half' },
  { ru: 'Караванщики платят за охрану вдвое: на тракте видели волков размером с телёнка.', en: 'Caravans pay double for guards: wolves the size of calves were seen on the road.', truth: 'half' },
  { ru: 'В горах нашли вход в дварфийскую шахту, закрытый изнутри.', en: 'They found a dwarven mine entrance in the hills — sealed from the inside.', truth: 'half' },
  { ru: 'Травница с рынка продаёт приворот, который «почти всегда» работает.', en: 'The market herbalist sells a love charm that works “almost every time”.', truth: 'half' },
  { ru: 'Король умер, об этом объявят после праздника урожая.', en: 'The king is dead; they will announce it after the harvest festival.', truth: 'false' },
  { ru: 'Под фундаментом храма замурован живой грешник.', en: 'A living sinner is walled up beneath the temple foundations.', truth: 'false' },
  { ru: 'Эльфы скупают рыжих котов. Зачем — лучше не знать.', en: 'The elves are buying up ginger cats. Better not to ask why.', truth: 'false' },
  { ru: 'В новолуние вода в фонтане превращается в вино.', en: 'On the new moon the fountain runs with wine.', truth: 'false' },
  { ru: 'Бургомистр по ночам обходит город в маске простолюдина.', en: 'The burgomaster walks the town at night masked as a commoner.', truth: 'false' },
  { ru: 'За хребтом видели летающий корабль с чёрными парусами.', en: 'A flying ship with black sails was seen beyond the ridge.', truth: 'false' },
  { ru: 'Кто проспит в этой таверне три ночи подряд, увидит вещий сон.', en: 'Sleep three nights running in this tavern and you will dream true.', truth: 'false' },
];

const tones = [
  { id: 'cozy', ru: 'Уютная', en: 'Cozy' },
  { id: 'seedy', ru: 'Злачная', en: 'Seedy' },
  { id: 'strange', ru: 'Странная', en: 'Uncanny' },
  { id: 'posh', ru: 'Чинная', en: 'Refined' },
];
const wealthLabels = [
  { ru: 'Трущобы', en: 'Slums' }, { ru: 'Среднее', en: 'Modest' }, { ru: 'Роскошь', en: 'Luxury' },
];
const sizeLabels = [
  { ru: 'Деревня', en: 'Village' }, { ru: 'Город', en: 'Town' }, { ru: 'Столица', en: 'Capital' },
];

export const TAVERN_DATA = {
  adjs, nouns, signs, atmos, crowd, food, drinks, names, races,
  traits, quirks, secrets, staff, patrons, rumors,
  tones, wealthLabels, sizeLabels,
};
